export const rules: string;
export const title: string;
export const h1: string;
export const magl: string;
export const tr: string;
export const rulesTB: string;
export const rule: string;
export const sw: string;
export const rulesSoccerBTN: string;
